# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ymc', '0002_video_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_asignado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ymc.Usuario'),
        ),
    ]
