# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ymc', '0005_auto_20170623_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='video_asignado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_usuario', to='ymc.Video'),
        ),
    ]
