# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ymc', '0006_auto_20170623_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='video_asignado',
        ),
        migrations.RemoveField(
            model_name='video',
            name='usuario',
        ),
        migrations.AddField(
            model_name='video',
            name='usuario_asignado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ymc.Usuario'),
        ),
    ]
