# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ymc', '0007_auto_20170623_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('cant_likes', models.IntegerField()),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ymc.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='cant_comentarios',
        ),
        migrations.RemoveField(
            model_name='video',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='video_asignado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ymc.Video'),
        ),
    ]
