# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ymc', '0008_auto_20170623_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ymc.Categoria'),
        ),
    ]
