# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymc', '0009_auto_20170623_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.FileField(default=None, upload_to=b'avatars/%Y/%m/%d/'),
        ),
    ]
