# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymc', '0010_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.FileField(default=None, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
