# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymc', '0013_auto_20170630_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='archivo',
            field=models.FileField(default=None, upload_to='videos/%Y/%m/%d'),
        ),
    ]
